version: '2'
services:
  base:
    build: .
    image: app:base
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
     - "5000:5000"
     - "8080:8080"
    volumes:
     - .:/usr/src/app